### ISSUE TITLE
Missing armors (one-off's and monster store)

### ISSUE THREAD

**Issue by CrossZiggy** [mrnohr/botw-armor#4]
Missing one-off armor pieces (champions tunic, circlets) and all monster shop equipment (dark link armor, monster masks).

**Comment by mrnohr** [comment]
I didn't add those at first because you can't dye most of those. But if it would be helpful to have, I could add them.

**Comment by CrossZiggy** [comment]
Definitely would be nice! Personally I love plenty of those (specifically, the champions tunic) so having access to them to mix-match would be great!


________________________________
Van: Matthew Nohr <notifications@github.com>
Verzonden: vrijdag 16 juni 2017 14:53
Aan: mrnohr/botw-armor
CC: CrossZiggy; Author
Onderwerp: Re: [mrnohr/botw-armor] Missing armors (one-off's and monster store) (#4)


I didn't add those at first because you can't dye most of those. But if it would be helpful to have, I could add them.

**Comment by mrnohr** [comment]
I added the champions tunic to start. I'll get the rest of them added as well.

**Comment by CrossZiggy** [comment]
Awesome! Thank you so much for this awesome tool 😃 I also mentioned it on reddit, but if you're planning to add DLC equipment I have the twilight set avaliable, although I'm sure someone on reddit has all of it.


________________________________
Van: Matthew Nohr <notifications@github.com>
Verzonden: vrijdag 16 juni 2017 15:32
Aan: mrnohr/botw-armor
CC: CrossZiggy; Author
Onderwerp: Re: [mrnohr/botw-armor] Missing armors (one-off's and monster store) (#4)


I added the champions tunic to start. I'll get the rest of them added as well.

**Comment by mrnohr** [comment]
I also have all the Amiibo armor, but I wasn't planning on adding that yet. I'm very excited about the DLC and the armor.

**Comment by CrossZiggy** [comment]
Ah alright, yeah the new armor's and DLC looks awesome! Thanks for the quick replies and adding of the Champ tunic for now, you're a godsent for fashionwild!


________________________________
Van: Matthew Nohr <notifications@github.com>
Verzonden: vrijdag 16 juni 2017 15:37
Aan: mrnohr/botw-armor
CC: CrossZiggy; Author
Onderwerp: Re: [mrnohr/botw-armor] Missing armors (one-off's and monster store) (#4)


I also have all the Amiibo armor, but I wasn't planning on adding that yet. I'm very excited about the DLC and the armor.

**Comment by mrnohr** [comment]
Added all the monster masks, jewelry, and a few other things!
